<?php

namespace AppBundle\Controller\Admin;

use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use AppBundle\Entity\Post;
use AppBundle\Form\PostType;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Class BlogController
 *
 * @Route("/tableau-de-bord/blog")
 *
 * @package AppBundle\Controller\Admin
 */
class BlogController extends Controller
{

    /**
     * Ajouter article
     *
     * @Route("/ajouter", name="admin_post_ajouter")
     * @Method({"GET","POST"})
     *
     * @param Request $request
     * @return mixed
     */
    public function ajouterAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $post = new Post();

        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /**
             * @var UploadedFile $image
             */
            $image = $post->getImage();

            if ($image instanceof UploadedFile) {
                $nom_image = $this->generateUniqueFilename().'.'.$image->guessExtension();

                $image->move(
                    $this->getParameter('upload_blog_directory'),
                    $nom_image
                );

                $post->setImage($nom_image);
            } else {
                $post->setImage('nao_blog_default.jpeg');
            }

            if ($post->getStatus()===$post::PUBLISHED || $post->getStatus()===$post::FEATURED) {
                $post->setPublishedAt(new \DateTime());
            }

            $em->persist($post);
            $em->flush();

            return $this->redirectToRoute('nao_accueil');
        }

        return $this->render('nao/admin/blog/ajouter.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}