<?php

namespace AppBundle\Repository;

/**
 * BirdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BirdRepository extends \Doctrine\ORM\EntityRepository
{

    public function count(){

        $nb = $this
            ->createQueryBuilder('b')
            ->select('count(b) as nb')
            ->getQuery()
            ->getSingleScalarResult();

        return $nb;

    }

}
