<?php

namespace AppBundle\Repository;

/**
 * BirdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BirdRepository extends \Doctrine\ORM\EntityRepository
{

    public function count(){

        $nb = $this
            ->createQueryBuilder('b')
            ->select('count(b) as nb')
            ->getQuery()
            ->getSingleScalarResult();

        return $nb;

    }

    /**
     * Get birds by name
     *
     * @param $name
     * @return array
     */
    public function byNomCourant($name)
    {
        return $this->createQueryBuilder('b')
            ->select('b.nomCourant', 'b.nomScientif', 'b.id')
            //->where('b.nomCourant LIKE :name')->setParameter('name', '%'.$name.'%')
            ->andWhere('b.nomCourant LIKE :name', 'b.id = b.ref')
            ->setParameter('name', '%'.$name.'%')
            ->getQuery()
            ->getResult();
    }

}
