app:
    resource: '@AppBundle/Controller/'
    type: annotation

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/nao.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

google_login:
    path: /login/check-google