security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_NATURALISTE
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_PARTICULIER: ROLE_PARTICULIER
        ROLE_NATURALISTE: ROLE_PARTICULIER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

            logout_on_user_change: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/observation/ajouter, role: [ROLE_PARTICULIER, ROLE_NATURALISTE, ROLE_ADMIN] }
        - { path: ^/observation/validation, role: [ROLE_NATURALISTE] }
        - { path: ^/tableau-de-bord/profile, role: [ROLE_PARTICULIER, ROLE_NATURALISTE, ROLE_ADMIN] }
        - { path: ^/tableau-de-bord/gestion, role: [ROLE_NATURALISTE, ROLE_ADMIN] }